Documentation:
  Enabled: false
LineLength:
  Max: 99
  Exclude:
    - 'spec/**/*_spec.rb'
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'app/admin/*.rb'
